export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST"
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS"
export const CREATE_RESTAURANT_FAILED = "CREATE_RESTAURANT_FAILED"

export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST"
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS"
export const GET_ALL_RESTAURANTS_FAILED = "GET_ALL_RESTAURANTS_FAILED"

export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST"
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS"
export const DELETE_RESTAURANT_FAILED = "DELETE_RESTAURANT_FAILED"

export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST"
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS"
export const UPDATE_RESTAURANT_FAILED = "UPDATE_RESTAURANT_FAILED"

export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST"
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS"
export const GET_RESTAURANT_BY_ID_FAILED = "GET_RESTAURANT_BY_ID_FAILED"

export const GET_RESTAURANT_BY_USER_ID_REQUEST = "GET_RESTAURANT_BY_USER_ID_REQUEST"
export const GET_RESTAURANT_BY_USER_ID_SUCCESS = "GET_RESTAURANT_BY_USER_ID_SUCCESS"
export const GET_RESTAURANT_BY_USER_ID_FAILED = "GET_RESTAURANT_BY_USER_ID_FAILED"

export const UPDATE_RESTAURANT_STATUS_REQUEST = "UPDATE_RESTAURANT_STATUS_REQUEST"
export const UPDATE_RESTAURANT_STATUS_SUCCESS = "UPDATE_RESTAURANT_STATUS_SUCCESS"
export const UPDATE_RESTAURANT_STATUS_FAILED = "UPDATE_RESTAURANT_STATUS_FAILED"

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST"
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED"

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST"
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS"
export const GET_ALL_EVENTS_FAILED = "GET_ALL_EVENTS_FAILED"

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST"
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED"

export const GET_RESTAURANT_EVENTS_REQUEST = "GET_RESTAURANT_EVENTS_REQUEST"
export const GET_RESTAURANT_EVENTS_SUCCESS = "GET_RESTAURANT_EVENTS_SUCCESS"
export const GET_RESTAURANT_EVENTS_FAILED = "GET_RESTAURANT_EVENTS_FAILED"

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED"

export const GET_RESTAURANT_CATEGORY_REQUEST = "GET_RESTAURANT_CATEGORY_REQUEST"
export const GET_RESTAURANT_CATEGORY_SUCCESS = "GET_RESTAURANT_CATEGORY_SUCCESS"
export const GET_RESTAURANT_CATEGORY_FAILED = "GET_RESTAURANT_CATEGORY_FAILED"