spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

jwt:
  secret: ${SECRET_KEY}

razorpay:
  api:
    test:
      key_id: ${RAZORPAY_KEY_ID}
      key_secret: ${RAZORPAY_KEY_SECRET}