export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST" 
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS" 
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED"

export const GET_USERS_ORDERS_REQUEST = "GET_USERS_ORDERS_REQUEST"
export const GET_USERS_ORDERS_SUCCESS = "GET_USERS_ORDERS_SUCCESS"
export const GET_USERS_ORDERS_FAILED = "GET_USERS_ORDERS_FAILED"

export const GET_USERS_NOTIFICATION_REQUEST = "GET_USERS_NOTIFICATION_REQUEST"
export const GET_USERS_NOTIFICATION_SUCCESS = "GET_USERS_NOTIFICATION_SUCCESS"
export const GET_USERS_NOTIFICATION_FAILED = "GET_USERS_NOTIFICATION_FAILED"