export const GET_INGREDIENTS = "GET_INGREDIENTS"
export const UPDATE_STOCK = "UPDATE_STOCK"

export const CREATE_INGREDIENT_REQUEST = "CREATE_INGREDIENT_REQUEST"
export const CREATE_INGREDIENT_SUCCESS = "CREATE_INGREDIENT_SUCCESS"
export const CREATE_INGREDIENT_FAILED = "CREATE_INGREDIENT_FAILED"

export const CREATE_INGREDIENT_CATEGORY_REQUEST = "CREATE_INGREDIENT_CATEGORY_REQUEST"
export const CREATE_INGREDIENT_CATEGORY_SUCCESS = "CREATE_INGREDIENT_CATEGORY_SUCCESS"
export const CREATE_INGREDIENT_CATEGORY_FAILED = "CREATE_INGREDIENT_CATEGORY_FAILED"

export const GET_INGREDIENT_CATEGORY_REQUEST = "GET_INGREDIENT_CATEGORY_REQUEST"
export const GET_INGREDIENT_CATEGORY_SUCCESS = "GET_INGREDIENT_CATEGORY_SUCCESS"
export const GET_INGREDIENT_CATEGORY_FAILED = "GET_INGREDIENT_CATEGORY_FAILED"