export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST"
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS"
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED"

export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST"
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS"
export const UPDATE_STOCK_FAILED = "UPDATE_STOCK_FAILED"

export const CREATE_INGREDIENT_REQUEST = "CREATE_INGREDIENT_REQUEST"
export const CREATE_INGREDIENT_SUCCESS = "CREATE_INGREDIENT_SUCCESS"
export const CREATE_INGREDIENT_FAILED = "CREATE_INGREDIENT_FAILED"

export const CREATE_INGREDIENT_CATEGORY_REQUEST = "CREATE_INGREDIENT_CATEGORY_REQUEST"
export const CREATE_INGREDIENT_CATEGORY_SUCCESS = "CREATE_INGREDIENT_CATEGORY_SUCCESS"
export const CREATE_INGREDIENT_CATEGORY_FAILED = "CREATE_INGREDIENT_CATEGORY_FAILED"

export const GET_INGREDIENT_CATEGORY_REQUEST = "GET_INGREDIENT_CATEGORY_REQUEST"
export const GET_INGREDIENT_CATEGORY_SUCCESS = "GET_INGREDIENT_CATEGORY_SUCCESS"
export const GET_INGREDIENT_CATEGORY_FAILED = "GET_INGREDIENT_CATEGORY_FAILED"